default: &default
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: comments_app_for_public_development

test:
  <<: *default
  adapter: mysql2
  username: root
  password:
  host: localhost
  database: comments_app_for_public_test

production: # ↓ここの記述が関係あるのでは？
  <<: *default
  adapter: postgresql
  url: <%= ENV['DATABASE_URL'] %>